polls/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .import views

app_name = "polls" 

urlpatterns =[
    path('', views.IndexView.as_view(), name='index'),
    # path('<int:question_id>/', views.detail, name='detail'),
    #path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('questions/', views.questions, name='questions'),

    path('<int:pk>/', views.Detail.as_view(), name = 'detail'),
    path('<int:pk>/results/', views.Results.as_view(), name = 'results')
]

project002/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls') ),
    #path('', include('polls.urls') ),
    
]

polls/models.py
from django.db import models
from django.db.models.fields import CharField
import datetime
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text= models.CharField(max_length=100)
    pub_date= models.DateTimeField('date published')
    active= models.BooleanField(default=True, blank=False)

    def __str__(self):
        return self.question_text

       
    @admin.display(boolean=True, ordering= "pub_date", description="is publised recently")
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        

class Choice(models.Model):
    question= models.ForeignKey(Question,on_delete= models.CASCADE)
    choice_text= models.CharField(max_length=100)
    votes= models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView




def index(request):
    return HttpResponse("Hello")


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {"q": question}
    return render(request,"polls/detail.html", context)


def results(request, question_id):
    response = f"Result for question id {question_id} "
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"q":question})
    # return HttpResponse(response)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        choice = request.POST["choice"]
        print(choice, "choice")
        selected_choice = get_object_or_404(Choice, pk=choice)
        print(selected_choice)
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {
            "q":question, "error_message": "option not selected"
        })
    selected_choice.votes +=1
    selected_choice.save()
    return HttpResponseRedirect(reverse("polls:results", args=(question_id,)))
    # return HttpResponse(f" voting on question id {question_id} ")


def questions(request):
    questions = Question.objects.all()
    #output = []
    #for q in questions:
    #    output.append(q.question_text)
    #output = ",".join(output)
    context = {"questions": questions , "content":"<h1>Polls App</h1>"}
    return render(request, "polls/index.html", context)


class IndexView(ListView):
    template_name = "polls/index.html"
    context_object_name = "questions"

    def get_queryset(self):
        return Question.objects.all()
        

class Detail(DetailView):
    template_name = "polls/detail.html"
    context_object_name = "q"
    model = Question


class Results(DetailView):
    template_name = "polls/results.html"
    context_object_name = "q"
    model = Question



    

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>

        <title>
            {% block title %} polls {% endblock %}
            
        </title>

        
    <link rel="stylesheet" href="{% static 'css/polls/style.css' %}">
    
    {% block extra_css %}  {% endblock extra_css %}
    </head>
    <body>
        {% block content  %}
        {% endblock %}


    </body>
</html>

templates/polls/detail.html
{% extends "base.html" %}
{% block content %}


{# <h1>{{q.question_text}}</h1> #}

{% comment %}
<ul>
    {% for choice in q.choice_set.all %}
    <li>{{choice.choice_text}}</li>
    {% endfor %}
</ul>
{% endcomment %}


{% lorem 2 random %}
<br>
<br>
{% now "DATE_FORMAT" %}
<br>
<br>
{% now "DATETIME_FORMAT" %}
<br>
<br>
{% now "Y" %}
<br>
<br>
{% now "M" %}
<br>
<br>
{% now "H" %}
<br>
<br>
{% now "d" %}
<br>
<br>
{% now "m" %}


<form action="{% url 'polls:vote' q.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ q.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in q.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input class="btn" type="submit" value="Vote">
    </form>

{% endblock %}

templates/polls/index.html
{% extends "base.html" %}

{% block title %}
index
{% endblock %}

{% block content %}

{% autoescape off %}

{{content}}

{% endautoescape %}

{% if questions %}

    <ul>
        {% for question in questions%}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}


{% endblock %}

templates/polls/results.html
{% extends "base.html" %}
{% block content %}

    <fieldset>
        <legend><h1>{{ q.question_text }}</h1></legend>
        {% for choice in q.choice_set.all %}
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}- {{choice.votes}}</label><br>
        {% endfor %}
    </fieldset>
    
    <a href="{% url 'polls:detail' q.id %}">vote again</a>
    
    {% endblock content %}

    {% block extra_css %} included extraaaa css {% endblock extra_css %}